---
title: Practical Machine Learning Project 
output:
  html_document:
    fig_height: 9
    fig_width: 9
---

## Background Introduction 
This is a homework assignment of Coursera’s MOOC Practical Machine Learning from Johns Hopkins University. Here is the introduction of the exercise:
"Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, we will use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants to predict the manner in which they did the exercise."

## Data Preprocessing  

```r
library(caret)
library(rpart)
```
### Get Data

```r
download.file('https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv', 'pml-training.csv')
download.file('https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv','pml-test.csv' )

trainingRaw   <- read.csv('pml-training.csv', na.strings=c("NA","#DIV/0!", ""))
testRaw       <- read.csv('pml-test.csv' , na.strings=c("NA", "#DIV/0!", ""))
```

### Clean data

Remove columns that contain NA missing values.

```r
trainRaw <- trainRaw[, colSums(is.na(trainRaw)) == 0] 
testRaw <- testRaw[, colSums(is.na(testRaw)) == 0] 
```
Remove cvtd_timestamp colums from the dataset since they are not relevant.

```r
train    <- trainRaw[,-c(1,5)]
test     <- testRaw[,-c(1,5)]
```


### Slice data
We are dividing data to 60% training and 40% testing sets.

```r
inTraining  <- createDataPartition(train$classe, p = 0.6, list = FALSE)
train    <- train[inTraining, ]
testing     <- train[-inTraining, ]
```

## Model
Fitting Random Forests

```r
classe <-train$classe
rf <-  train(classe ~ ., data=train, method="rf", trControl=trainControl(method="cv", 5), ntree=50)
```

```
## Random Forest 

## 11776 samples
##   57 predictor
##   5 classes: 'A', 'B', 'C', 'D', 'E' 

## No pre-processing
## Resampling: Cross-Validated (5 fold) 

## Summary of sample sizes: 9421, 9421, 9420, 9421, 9421 

## Resampling results across tuning parameters:

##  mtry  Accuracy   Kappa      Accuracy SD  Kappa SD   
##   2    0.9908289  0.9883984  0.002592738  0.003280437
##  31    0.9966032  0.9957032  0.001163140  0.001471274
##  61    0.9951596  0.9938771  0.001147357  0.001452170

## Accuracy was used to select the optimal model using  the largest value.
## The final value used for the model was mtry = 31. 
```
Confusion Matrix

```r
predictRf <- predict(rf, testing)
confusionMatrix(testing$classe, predictRf)
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1343    1    0    0    1
##          B    8  908    4    0    0
##          C    0    1  793    5    0
##          D    0    0   14  798    1
##          E    0    0    0    6  871
## 
## Overall Statistics
##                                          
##                Accuracy : 1          
##                  95% CI : (0.9992, 1)
##     No Information Rate : 0.285         
##     P-Value [Acc > NIR] : < 2.2e-16      
##                                          
##                   Kappa : 1         
##  Mcnemar's Test P-Value : NA             
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity             1.000   1.0000   1.0000   1.0000   1.0000
## Specificity             1.000   1.0000   1.0000   1.0000   1.0000
## Pos Pred Value          1.000   1.0000   1.0000   1.0000   1.0000
## Neg Pred Value          1.000   1.0000   1.0000   1.0000   1.0000
## Prevalence              0.285   0.1927   0.1683   0.1693   0.1848
## Detection Rate          0.285   0.1927   0.1683   0.1693   0.1848
## Detection Prevalence    0.285   0.1927   0.1683   0.1693   0.1848
## Balanced Accuracy       1.000   1.0000   1.0000   1.0000   1.0000
```

```r
err <- 1 - as.numeric(confusionMatrix(testing$classe, rf)$overall[1])
err
```
The estimated out-of-sample error is 0.01%

## Predict Test Data Set


```r
result <- predict(rf, test[, -length(names(test))])
```


